name: newton_2
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.3
  rxdart: ^0.23.1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

